import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Moisés',
      email: 'admin@admin.com',
      password: bcrypt.hashSync('12345678'),
      isAdmin: true,
    },
    {
      name: 'Lennon',
      email: 'user@user.com',
      password: bcrypt.hashSync('12345678'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Caja de mascarillas',
      slug: 'caja-de-mascarillas-desechables',
      category: 'Salud',
      image: '/images/CAJA-DE-DESECHABLES-CELESTES-150x150.jpg',
      isFeatured: true,
      price: 70,
      brand: '',
      countInStock: 20,
      tags: 'mascarilla 3 capas, mascarilla 3 pliegues, mascarilla ajustable, mascarilla barata, mascarilla desechable',
      description: 'mascarilla 3 capas, con 3 pliegues, ajustable, desechable.',
    },
    {
      name: 'Letrero corporativo',
      slug: 'Letrero-corporativo',
      category: 'Placas acero',
      image: '/images/Placa-de-acero-inoxidable_con-logo-150x150.jpg',
      isFeatured: true,
      price: 70,
      brand: '',
      countInStock: 20,
      tags: 'chile, fabrica de letreros, fábrica de placas, fabricación de placas, letrero de acero, letreros chile, placa conmemorativa, placa de gobierno, placa de reconocimiento, placa e acero para muro, placa fachada, placa grabada, placa grabada conce, placa inaugural, placa laser, placa monumento, placa para constructora, placa para edificio, placa para memorial, placa para obras terminadas, placa proyecto, placa sercotec, placas concepción, placas corfo, placas de acero, placas de gobierno, placas grabadas conce, placas grabadas en relieve, placas hechas a medida, placas para nichos, placas personalizadas, plancha metálica con logo, plancha metálica grabada, proyecto corfo',
      description:
        'Placa de acero inoxidable fotograbada al ácido, en bajo relieve, horneada y lacada. Entrega entre 3-5 días hábiles. Kit de instalación opcional: pernos, distanciadores y tapas embellecedoras. Todas las medidas y espesores (hechas a pedido) . Con o sin curvatura. Entrega entre 3 y 5 días hábiles.',
    },
    {
      name: 'Placa proyecto Corfo',
      slug: 'Placa-proyecto-corfo',
      category: 'Placas acero',
      image: '/images/plc-.acero_-1024x651-150x150.jpg',
      isFeatured: true,
      price: 70,
      brand: '',
      countInStock: 20,
      tags: 'letrero de aceo, placa constructoras, placa corfo, placa de acero, placa fachada, placa grabada, placa inauguración, placa inaugural, placa monolito, placa para edificio, proyecto corfo',
      description:
        'Placa de acero inoxidable, grabada en bajo relieve, superficie brillante lacada. Incluye perforaciones y embellecedores de acero inox. Entrega entre 4 y 5 días hábiles.',
    },
    {
      name: 'Placa para tumba',
      slug: 'Placa-para-tumba',
      category: 'Placas acero',
      image: '/images/lápida-1-1-e1611346686460-600x364.png',
      isFeatured: true,
      price: 70,
      brand: '',
      countInStock: 20,
      tags: 'difunto, epigrafe, epitafio, lapida, lapida conmemorativa, lápida de muro, lapida mural, memorial, obituario, placa cementerio, placa de agradecimiento, placa de pared, placa difunto, placa funeral, placa grabada, placa monolito, placa mortuoria, placa para monumento, placa para sepultura, placa parque, placa parque sendero, placa personalizada, placa reconocimiento, placa tumba, placas para constructoras, placas para nicho, placas religiosas, plancha grabada',
      description:
        'Producto eterno, no necesita mantención ni limpieza. Es posible fotograbar en bajo relieve la fotografía de la persona fallecida por $10.000 adicional. Entrega entre 4 y 5 dás.',
    },
    {
      name: 'Réplica de título profesional',
      slug: 'Réplica-de-título-profesional',
      category: 'Placas acero',
      image: '/images/Placa-de-acero-inoxidable_fotograbada_3-150x150.jpg',
      isFeatured: true,
      price: 70,
      brand: '',
      countInStock: 20,
      tags: 'cuadro corporativo, distinciones médicas, premio mejor alumno, premios sector salud, recuerdo licenciatura, regalo corporativo, regalo doctor concepción, regalo graduacion',
      description:
        'Placa de acero inoxidable fotograbada al ácido en bajo relieve sobre una base de madera nativa de 56×45 cm. Con caja de regalo. Es posible reproducir estampillas, timbres de agua y firmas, con la autorización del titulado.. Entrega entre 4 -5 días hábiles.',
    },
    {
      name: 'Copas en todas las medidas',
      slug: 'Copas-en-todas-las-medidas',
      category: 'Trofeos y copas',
      image: '/images/montaje-300x200.png',
      isFeatured: true,
      price: 70,
      brand: '',
      countInStock: 20,
      tags: 'copas campeonatos, fabrica de copas deportivas, fabrica de trofeos, fabricante de trofeos, olimpiadas, premio equipos de futbol, premios deportivos, proveedot trofeos de bronce, proyectos deportivos, trofeos conce, trofeos todas las medidas, venta de trofeos a todo chile, venta de trofeos en chile.',
      description:
        'Todas las copas son metálicas bañadas en bronce, con cintas tricolor en las orejas. Descuento a mayoristas, entrega inmediata. Tamaños: 30 cm, 35 cm, 40 cm, 45 cm, 50 cm. Despacho a regiones.',
    },
    {
      name: 'Trofeos de música',
      slug: 'Trofeos-de-música',
      category: 'Trofeos y copas',
      image: '/images/trofeos-musicales-300x140.jpg',
      isFeatured: true,
      price: 70,
      brand: '',
      countInStock: 20,
      tags: 'concierto, encuentros de musica, festival, festival de la musica, recuerdo concierto, regalo cantantes, trofeo festival de la voz, trofeo llave de sol, trofeo musical',
      description:
        'Mínimo 3 unidades. Incluye placa grabada. Caja de regalo opcional.',
    },
    {
      name: 'Trofeo de fútbol (56Cm. dealto)',
      slug: 'Trofeo-de-fútbol-56CM.-de-alto',
      category: 'Trofeos y copas',
      image: '/images/copa-con-tapa-56-cm-186x300.jpg',
      isFeatured: true,
      price: 70,
      brand: '',
      countInStock: 20,
      tags: 'copa campeon, copa deportiva, trofeo, trofeo conce, trofeo de bronce, trofeo fútbol',
      description: 'Se venden por unidad. Incluye grabado de placa.',
    },
    {
      name: 'Trofeo (1 Metro)',
      slug: 'TROFEO-1-METRO-Y-10-CM.',
      category: 'Trofeos y copas',
      image: '/images/trofeo-110-cm-72.000-con-placa-103x300.jpg',
      isFeatured: true,
      price: 70,
      brand: '',
      countInStock: 20,
      tags: 'fabrica de trofeos en Chile, trofeo gigante, trofeos conce, trofeos de 1 metro de alto, trofeos entrega inmediata, trofeos fútbol, trofeos grandes.',
      description:
        'Trofeo metálico bañado en bronce de 1,10 metro de alto. Espacio para incluir 3 logos. Descuento a mayoristas. Se vende como insumo o con la opción de los logos en resina o grabados en metalex con placa grabada. Entrega inmediata.',
    },
    {
      name: 'Medalla zamac',
      slug: 'Medalla-zamac-con-cuño',
      category: 'Medallas',
      image: '/images/zamac-envejecida-276x300.jpg',
      isFeatured: true,
      price: 70,
      brand: '',
      countInStock: 20,
      tags: 'medallas, grabado de medallas, medallas chile, fabricación de medallas',
      description: 'Mínimo 120 unidades. Entrega en 7 días hábiles',
    },
    // {
    //   name: 'Free Shirt',
    //   slug: 'free-shirt',
    //   category: 'Shirts',
    //   image: '/images/shirt1.jpg',
    //   isFeatured: true,
    //   featuredImage: '/images/banner1.jpg',
    //   price: 70,
    //   brand: 'Nike',
    //   rating: 4.5,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: 'A popular shirt',
    // },
    // {
    //   name: 'Fit Shirt',
    //   slug: 'fit-shirt',
    //   category: 'Shirts',
    //   image: '/images/shirt2.jpg',
    //   isFeatured: true,
    //   featuredImage: '/images/banner2.jpg',
    //   price: 80,
    //   brand: 'Adidas',
    //   rating: 4.2,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: 'A popular shirt',
    // },
    // {
    //   name: 'Slim Shirt',
    //   slug: 'slim-shirt',
    //   category: 'Shirts',
    //   image: '/images/shirt3.jpg',
    //   price: 90,
    //   brand: 'Raymond',
    //   rating: 4.5,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: 'A popular shirt',
    // },
    // {
    //   name: 'Golf Pants',
    //   slug: 'golf-pants',
    //   category: 'Pants',
    //   image: '/images/pants1.jpg',
    //   price: 90,
    //   brand: 'Oliver',
    //   rating: 4.5,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: 'Smart looking pants',
    // },
    // {
    //   name: 'Fit Pants',
    //   slug: 'fit-pants',
    //   category: 'Pants',
    //   image: '/images/pants2.jpg',
    //   price: 95,
    //   brand: 'Zara',
    //   rating: 4.5,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: 'A popular pants',
    // },
    // {
    //   name: 'Classic Pants',
    //   slug: 'classic-pants',
    //   category: 'Pants',
    //   image: '/images/pants3.jpg',
    //   price: 75,
    //   brand: 'Casely',
    //   rating: 4.5,
    //   numReviews: 10,
    //   countInStock: 20,
    //   description: 'A popular pants',
    // },
  ],
};

export default data;
